name: CI Model with Torch Hub

on:
  release:
    types: [released]

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.ref_name }}

jobs:
  torchhub:
    name: Load Model with Torch Hub
    runs-on: ubuntu-latest
    container:
      # TODO: change image container
      image: ruhyadi/yolov5n:cvat-v1.3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load Model with Python
        run: |
          python3 hubconf.py --repository ${{ github.repository }} --tag ${{ github.ref_name }}