name: CI Model with Torch Hub

on:
  release:
    types: [released]

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.ref_name }}

jobs:
  nuclio-container:
    name: Nulcio Container
    runs-on: ubuntu-latest
    container:
      image: quay.io/nuclio/dashboard:1.5.16-amd64
      volumes:
        - /tmp:/tmp
        - /var/run/docker.sock:/var/run/docker.sock
      env:
        no_proxy: 172.28.0.1,${no_proxy}
        NUCLIO_CHECK_FUNCTION_CONTAINERS_HEALTHINESS: 'true'
        NUCLIO_DASHBOARD_DEFAULT_FUNCTION_MOUNT_MODE: 'volume'
      ports:
        - '8070:8070'
    steps:
      - name: Success Running
        run: echo "🎉 Nuclio Container Success Running."

  deploy-model:
    needs: [ nuclio-container ]
    name: Deploy Model 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 

      - name: Deploy Model
        uses: ruhyadi/nuclio-model-deployment@v2
        with:
          model-dir: ./

      - name: Model Logs
        uses: jwalton/gh-docker-logs@v2

  delete-release:
    needs: [ deploy-model ]
    name: Delete Release
    runs-on: ubuntu-latest
    if: always() && (needs.nuclio-container.result == 'failure')
    steps:
      - name: Delete Tag and Release 
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: ${{ github.ref_name }}
          repo: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}